name: combatcv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - aom=3.6.1=h63175ca_0
  - blas=1.0=mkl
  - brotlicffi=1.1.0.0=py310h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.12=h4c7d964_0
  - cairo=1.16.0=h0ac17fb_1012
  - certifi=2025.11.12=py310haa95532_0
  - cffi=2.0.0=py310h02ab6af_1
  - charset-normalizer=3.4.4=py310haa95532_0
  - cpuonly=2.0=0
  - dav1d=1.2.1=hcfcfb64_0
  - expat=2.7.3=h9214b88_0
  - ffmpeg=5.1.2=gpl_h8bb4bc8_112
  - filelock=3.20.0=py310haa95532_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=hbde0cde_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freeglut=3.2.2=he0c23c2_3
  - freetype=2.13.3=h0620614_0
  - gettext=0.22.5=h5728263_3
  - gettext-tools=0.22.5=h5a7288d_3
  - giflib=5.2.2=h7edc060_0
  - glib=2.84.0=h3d4babf_0
  - glib-tools=2.84.0=h4394cf3_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py310h827c3e9_0
  - graphite2=1.3.14=hac47afa_2
  - gst-plugins-base=1.22.9=h001b923_1
  - gstreamer=1.22.9=hb4038d2_1
  - harfbuzz=6.0.0=he256f1b_0
  - icu=70.1=h0e60522_0
  - idna=3.11=py310haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jasper=2.0.33=hc2e4405_1
  - jinja2=3.1.6=py310haa95532_0
  - jpeg=9f=ha349fce_0
  - krb5=1.20.1=heb0366b_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libasprintf=0.22.5=h5728263_3
  - libasprintf-devel=0.22.5=h5728263_3
  - libblas=3.9.0=1_h8933c1f_netlib
  - libcblas=3.9.0=13_hc41557d_netlib
  - libclang=15.0.7=default_h3a3e6c3_5
  - libclang13=15.0.7=default_hf64faad_5
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libgettextpo=0.22.5=h5728263_3
  - libgettextpo-devel=0.22.5=h5728263_3
  - libglib=2.84.0=h7025463_0
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - liblapack=3.9.0=13_h018ca30_netlib
  - liblapacke=3.9.0=13_h0d55cca_netlib
  - libogg=1.3.5=h2466b09_1
  - libopencv=4.7.0=py310h90026ac_1
  - libopus=1.5.2=h2466b09_0
  - libpng=1.6.50=h46444df_0
  - libprotobuf=3.21.12=h12be248_2
  - libsqlite=3.51.0=hf5d6505_0
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libvorbis=1.3.7=h5112557_2
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.9=h741aa76_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=3.0.2=py310h827c3e9_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py310h827c3e9_2
  - mkl_fft=1.3.11=py310h827c3e9_0
  - mkl_random=1.2.8=py310hc64d2fc_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py310haa95532_0
  - msys2-conda-epoch=20160418=1
  - networkx=3.4.2=py310haa95532_0
  - numpy=1.26.4=py310h055cbcc_0
  - numpy-base=1.26.4=py310h65a83cf_0
  - opencv=4.7.0=py310h5588dad_1
  - openh264=2.3.1=h63175ca_2
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pcre2=10.44=h99c9b8b_2
  - pillow=11.1.0=py310h096bfcc_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h5112557_1
  - py-opencv=4.7.0=py310hbbfc1a7_1
  - pycparser=2.23=py310haa95532_0
  - pysocks=1.7.1=py310haa95532_1
  - python=3.10.19=h981015d_0
  - python_abi=3.10=2_cp310
  - pytorch=2.5.1=py3.10_cpu_0
  - pytorch-mutex=1.0=cpu
  - pyyaml=6.0.2=py310h827c3e9_0
  - qt-main=5.15.8=h720456b_6
  - requests=2.32.5=py310haa95532_1
  - setuptools=80.9.0=py310haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - svt-av1=1.4.1=h63175ca_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.15=hf199647_0
  - torchaudio=2.5.1=py310_cpu
  - torchvision=0.20.1=py310_cpu
  - typing_extensions=4.15.0=py310haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.5.0=py310haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_1
  - x264=1!164.3095=h8ffe710_2
  - x265=3.5=h2d74725_3
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - absl-py==2.3.1
      - attrs==25.4.0
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - jax==0.6.2
      - jaxlib==0.6.2
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - matplotlib==3.10.7
      - mediapipe==0.10.21
      - ml-dtypes==0.5.3
      - opencv-contrib-python==4.11.0.86
      - opt-einsum==3.4.0
      - pandas==2.3.3
      - polars==1.35.2
      - polars-runtime-32==1.35.2
      - protobuf==4.25.8
      - psutil==7.1.3
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sentencepiece==0.2.1
      - six==1.17.0
      - sounddevice==0.5.3
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - tzdata==2025.2
      - ultralytics==8.3.228
      - ultralytics-thop==2.0.18
prefix: C:\Users\noahr\anaconda3\envs\combatcv
